spring.application.name=VestaboardAPI

# Enable or disable LiveReload (enabled by default)
spring.devtools.livereload.enabled=false
logging.level.org.springframework.web=DEBUG
# Disable restart feature (enabled by default)
spring.devtools.restart.enabled=false